# It contains all the configs required in the project

META-DATA:
  api_key : "AIzaSyAx6ATpIlbfQELX2xDMOwQO5cXZwZXZJAw"
  search_id : "976d4d8794ffe4873"
  search_type : "customsearch"
  version : "v1"
PARAPHRASE:
  tokens : "Vamsi/T5_Paraphrase_Paws"
  model_path : "init_model/plagarism"
  num_outputs : 3